### ISSUE TITLE
Unexpected failure during module execution

### ISSUE THREAD

**Issue by RolfKoenders** [UnsignedLong/ansible-nginx-letsencrypt#6]
### Description

Would really like to use this to automate my reverse proxy host but ill keep getting this Ansible error when running the playbook. 

- The inventory file is updated.
- I have modified my groups vars accordingly to the examples.

### Environment
Remote host is an LXC container running Ubuntu 14.04.

### Stacktrace
 ```bash
$ ansible-playbook -K -i inventory nginx-offloading-letsencrypt.yml -vvv
Using /etc/ansible/ansible.cfg as config file
SUDO password: 

PLAYBOOK: nginx-offloading-letsencrypt.yml *************************************
1 plays in nginx-offloading-letsencrypt.yml

PLAY [reverseproxy] ************************************************************

TASK [setup] *******************************************************************
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<192.168.2.116> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.2.116> SSH: EXEC sshpass -d21 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o User=root -o ConnectTimeout=10 -o ControlPath=/home/rolf/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.2.116 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 511, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 584, in _execute_module
    tmp = self._make_tmp_path(remote_user)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 224, in _make_tmp_path
    tmpdir =  self._remote_expand_user(C.DEFAULT_REMOTE_TMP, sudoable=False)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 506, in _remote_expand_user
    initial_fragment = data['stdout'].strip().splitlines()[-1]
IndexError: list index out of range

fatal: [192.168.2.116]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
        to retry, use: --limit @/home/rolf/Documents/projects/ansible-nginx-letsencrypt/nginx-offloading-letsencrypt.retry

PLAY RECAP *********************************************************************
192.168.2.116              : ok=0    changed=0    unreachable=0    failed=1  
```

**Comment by RolfKoenders** [comment]
Solved this error by downgrading Ansible to version `2.2.1.0`. Created a virtualenv to run this playbook.

**Comment by UnsignedLong** [comment]
Which ansible version did you use before downgrading?

**Comment by RolfKoenders** [comment]
```ansible 2.2.2.0```
